<h1>
  About <span class="thin">Studia Phaenomenologica</span>
</h1>

<p><em>Studia Phaenomenologica</em> is a peer-reviewed yearbook in phenomenology and hermeneutics, founded in 2001 by Gabriel Cercel and Cristian Ciocan. It is edited by the <a href="" target="_blank">Romanian Society for Phenomenology</a> and <a href="" target="_blank">Humanitas Publishing House</a>. All articles are blind-refereed except when invited.</p>

<table class="table table-striped table-condensed table-hover">
  <tr><td style="min-width: 10em;">Editor-In-Chief:</td><td>Cristian Ciocan</td></tr>
  <tr><td>Book-Review-Editor:</td><td>Christian Ferencz-Flatz</td></tr>
  <tr><td>Editorial Assistant:</td><td>Remus Breazu</td></tr>
  <tr><td>Editorial Board:</td><td>Roxana Băiașu, Victor Biceaga, Virgil Ciomoș, Ion Copoeru, Mădălina Diaconu, Paul Marinescu, Bogdan Mincă, Attila Szigeti</td></tr>
  <tr><td>Advisory Board:</td><td>Renaud Barbaras, Elizabeth A. Behnke, Rudolf Bernet, Adina Bozga, Walter Biemel, Jean-François Courtine, Renato Cristin, Françoise Dastur, Natalie Depraz, Parvis Emad, Eliane Escoubas, Jean Greisch, Günter Figal, Marion Heinz, Klaus Held, Fr.-W. von Herrmann, Theodore Kisiel, Jean-Yves Lacoste, Gabriel Liiceanu, Jean-Luc Marion, Otto Pöggeler, Delia Popa, Marc Richir, Hans Rainer Sepp, Helmuth Vetter, Bernard Waldenfels</td></tr>
</table>
