<div class="row">
  <div class="col-sm-5">
    <img src="/assets/images/<?=$issue['cover']?>" class="img-responsive" alt="Studia Phaenomenologica Cover">
  </div>
  <div class="col-sm-7">
        <h1> <?=$issue['title']?> </h1>
        <h3> <?=$journal['journalTitle'].' - '.$journal['journalSubtitle']?> </h3>
        <h3> <?=$issue['number'].' / '.$issue['year'] ?> </h3>
        Journal Editor: <?=$journal['journalEditor']?><br />
        Issue Coordinators: <?php echo showCoordinators($issue); ?><br />
        ISBN: <?=$issue['isbnPaperback']?> (print) / <?=$issue['isbnEbook']?> (eBook)<br />
        ISSN: <?=$journal['issnPrint'] ?> (print) / <?=$journal['issnOnline'] ?> (online)<br />
        Pages: <?=$issue['pages']?><br />
        Size: <?=$issue['size']?><br />
        Available in both printed and eBook version.
        <div>
          <?php echo $order; ?>
        </div>
        <div>
          <a class="btn btn-warning btn-xs" role="button" href="index.php?page=issue&id=13">See Contents</a>
          <a class="btn btn-warning btn-xs" role="button" href="index.php?page=issues">Other issues</a>
        </div>
        <div>
          <?php //echo showContents($issue['contents']); ?>
          <?php echo $toc; ?>
        </div>
  </div>
</div>
