<div class="row">
  <div class="col-sm-5">
    <img src="/assets/images/<?=$issue['cover']?>" class="img-responsive" alt="Studia Phaenomenologica Cover">
  </div>
  <div class="col-sm-7">
        <h1> <?php echo $issue['title']; ?> </h1>
        <h3> <?php echo $journal['journalTitle'].' - '.$issue['number'].' / '.$issue['year']; ?> </h3>
        Journal Editor: <?php echo $journal['journalEditor']; ?><br />
        Issue Coordinators: 
          <?php for ($i=0; $i<count($issue['issueCoordinator']); $i++) : ?>
            <?php echo $issue['issueCoordinator'][$i].($i>0 ? ' ' : ' & '); ?>
          <?php endfor; ?>
          <br />
        ISBN: <?php echo $issue['isbnPaperback']; ?> (print) / <?php echo $issue['isbnEbook']; ?> (eBook)<br />
        ISSN: <?php echo $journal['issnPrint']; ?> (print) / <?php echo $journal['issnOnline']; ?> (online)<br />
        Pages: <?php echo $issue['pages']; ?><br />
        Size: <?php echo $issue['size']; ?><br />
        Available in both printed and eBook version.<br />
        Publishers: 
          <?php for ($i=0; $i<count($journal['publisher']); $i++) : ?>
            <a href="<?php echo $journal['publisher'][$i]['url']; ?>" target="_blank">
              <?php echo $journal['publisher'][$i]['name']; ?>
            </a>
            <?php echo ($i>0 ? ' ' : ' & '); ?> 
          <?php endfor; ?>
          <br />
        <div>
          <?php echo $order; ?>
        </div>
        <div>
          <?php echo $toc; ?>
        </div>
  </div>
</div>
