<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Studia Phaenomenologica</title>

    <!-- Bootstrap -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <!-- Simple Sidebar CSS -->
    <link href="/assets/css/simple-sidebar.css" rel="stylesheet">
    <!-- Add Font-Awesome CSS-->
    <link href="/assets/css/font-awesome.min.css" rel="stylesheet">
    <!-- Import Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <!-- Our custom CSS file -->
    <link href="/assets/css/main.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="/">
                        home
                    </a>
                </li>
                <li>
                    <a href="/issues">all issues</a>
                </li>
                <li>
                    <a href="/editorial-board">editorial board</a>
                </li>
                <li>
                    <a href="/call-for-papers">call for papers</a>
                </li>
                <li>
                    <a href="/buy-subscribe">buy & subscribe</a>
                </li>
                <li>
                    <a href="/how-to-sumit-articles">submit articles</a>
                </li>
                <li>
                    <a href="/contact">contact us</a>
                </li>
                <li>
                    <a href="http://www.pdcnet.org/pdc/bvdb.nsf/journal?openform&journal=pdc_studphaen" target="_blank">online access <i class="fa fa-external-link-square"></i></a> 
                </li>
                <li>
                  <p class="footer">&copy; 2010<script>new Date().getFullYear()>2010&&document.write("-"+new Date().getFullYear());</script></p>
                </li>
            </ul>

        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                      <!-- Toggle Menu -->
                      <a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><i class="fa fa-bars"></i></a>
                      <?php echo $body; ?>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/assets/js/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/assets/js/bootstrap.min.js"></script>
    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
</body>
</html>
