<?php if(isset($article['abstract'])){ ?>
<a data-toggle="collapse" href="#<?php echo $article['hashID']; ?>" aria-expanded="false" aria-controls="<?php echo $article['hashID']; ?>">
  <p class="article-title">
    <?php echo $article['authors']; ?> - 
    <em>
      <?php echo $article['title']; ?>
    </em>
  </p>
</a>
<div class="collapse" id="<?php echo $article['hashID']; ?>">
  <small class="abstract">
    <?php echo $article['abstract']; ?>
  </small>
</div>

<?php } else { ?>
<p class="article-title">
  <?php echo $article['authors'];?> - 
  <em>
    <?php echo $article['title'];?>
  </em>
</p>
<?php } ?>
